/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package human;
/**
 *
 * @author Gulraiz
 */

import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.event.ChangeListener;


public class LeftPanel extends JPanel {

    /**
     * Creates new form NewJPanel
     */
    public LeftPanel(String[] bones, ActionListener aListner, ChangeListener cListner) {
        initComponents(bones,aListner,cListner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String[] bones, ActionListener aListner, ChangeListener cListner) {

        jPanel1 = new JPanel();
        gender = new JComboBox();
        jLabel1 = new JLabel();
        jsHeight = new JSlider();
        biCristal = new JSlider();
        jsBitroch = new JSlider();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jsWaist = new JSlider();
        jLabel5 = new JLabel();
        txtHeight = new JTextField();
        txtWeight = new JTextField();
        txtBust = new JTextField();
        txtWaist = new JTextField();
        jsHip = new JSlider();
        jsInseam = new JSlider();
        jsNeck = new JSlider();
        jLabel6 = new JLabel();
        txtHip = new JTextField();
        jLabel7 = new JLabel();
        txtInseam = new JTextField();
        txtNeck = new JTextField();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jsSleeve = new JSlider();
        txtSleeve = new JTextField();

        jPanel1.setBorder(BorderFactory.createTitledBorder(null, "BODY MEASUREMENTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        gender.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gender.setModel(new DefaultComboBoxModel(new String[] { "Male", "Female" }));
        gender.setName("gender");
        gender.addActionListener(aListner);
        gender.setActionCommand("gender");
        /*gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });*/

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("GENDER");
        
        

        jsHeight.setMinorTickSpacing(1);
        jsHeight.setMaximum(2084);
        jsHeight.setValue(1508);
        jsHeight.setMinimum(1248);
        jsHeight.setName("jsHeight");
        jsHeight.setPaintLabels(true);
        jsHeight.setPaintTicks(true);
        jsHeight.setSnapToTicks(true);
        jsHeight.setValueIsAdjusting(true);
        jsHeight.addChangeListener(cListner);

        biCristal.setMinorTickSpacing(1);
        biCristal.setMaximum(579);
        biCristal.setValue(239);
        biCristal.setMinimum(239);
        biCristal.setName("biCristal");
        biCristal.setPaintLabels(true);
        biCristal.setPaintTicks(true);
        biCristal.setSnapToTicks(true);
        biCristal.addChangeListener(cListner);

        jsBitroch.setMinorTickSpacing(1);
        jsBitroch.setMaximum(492);
        jsBitroch.setValue(400);
        jsBitroch.setMinimum(305);
        jsBitroch.setName("jsBitroch");
        jsBitroch.setPaintLabels(true);
        jsBitroch.setPaintTicks(true);
        jsBitroch.setSnapToTicks(true);
        jsBitroch.addChangeListener(cListner);


        jsWaist.setMinorTickSpacing(1);
        jsWaist.setMaximum(55);
        jsWaist.setValue(31);
        jsWaist.setMinimum(22);
        jsWaist.setName("jsWaist");
        jsWaist.setPaintLabels(true);
        jsWaist.setPaintTicks(true);
        jsWaist.setSnapToTicks(true);
        jsWaist.addChangeListener(cListner);

        jsHip.setMinorTickSpacing(1);
        jsHip.setMaximum(66);
        jsHip.setValue(41);
        jsHip.setMinimum(31);
        jsHip.setName("jsHip");
        jsHip.setPaintLabels(true);
        jsHip.setPaintTicks(true);
        jsHip.setSnapToTicks(true);
        jsHip.addChangeListener(cListner);

        jsInseam.setMinorTickSpacing(1);
        jsInseam.setMaximum(37);
        jsInseam.setValue(29);
        jsInseam.setMinimum(22);
        jsInseam.setName("jsInseam");
        jsInseam.setPaintLabels(true);
        jsInseam.setPaintTicks(true);
        jsInseam.setSnapToTicks(true);
        jsInseam.addChangeListener(cListner);

        jsNeck.setMinorTickSpacing(1);
        jsNeck.setMaximum(19);
        jsNeck.setValue(13);
        jsNeck.setMinimum(10);
        jsNeck.setName("jsNeck");
        jsNeck.setPaintLabels(true);
        jsNeck.setPaintTicks(true);
        jsNeck.setSnapToTicks(true);
        jsNeck.addChangeListener(cListner);

        jsSleeve.setMinorTickSpacing(1);
        jsSleeve.setMaximum(37);
        jsSleeve.setValue(30);
        jsSleeve.setMinimum(20);
        jsSleeve.setName("jsSleeve");
        jsSleeve.setPaintLabels(true);
        jsSleeve.setPaintTicks(true);
        jsSleeve.setSnapToTicks(true);
        jsSleeve.addChangeListener(cListner);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("HEIGHT ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("BILIOCRISTAL DISTANCE");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("BITROCHANTERIC BREADTH STANDING");
        

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("WAIST GIRTH (in)");

        txtHeight.setText("71.0 mm");
        txtWeight.setText("115.0 mm");
        txtBust.setText("38.0 mm");
        txtWaist.setText("31.0 in");
        txtHip.setText("41.0 in");
        txtInseam.setText("29.0 in");
        txtNeck.setText("13.0 in");
        txtSleeve.setText("30.0 in");
        
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("LOW HIP GIRTH ( in )");


        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("INSEAM ");

        
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("MID NECK GIRTH");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("SLEEVE LENGTH");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jsHip, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                .addComponent(jLabel7, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jsInseam, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jsNeck, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(txtInseam, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNeck, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHip, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jsSleeve, GroupLayout.PREFERRED_SIZE, 248, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSleeve, GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jsHeight, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHeight, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(biCristal, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtWeight, GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jsBitroch, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBust, GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jsWaist, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWaist, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {txtHeight, txtWeight, txtBust, txtWaist, txtHip, txtInseam, txtNeck, txtSleeve});

        jPanel1Layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {jsHeight, biCristal, jsBitroch, jsWaist, jsHip, jsInseam, jsNeck, jsSleeve});

        jPanel1Layout.linkSize(SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gender, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHeight, GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jsHeight, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtWeight, GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(biCristal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBust, GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jsBitroch, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(txtWaist, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsWaist, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsHip, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtHip, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jsInseam, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInseam, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jsNeck, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNeck, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(txtSleeve, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsSleeve, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(SwingConstants.VERTICAL, new java.awt.Component[] {jsHeight, biCristal, jsBitroch, jsWaist, jsHip, jsInseam, jsNeck, jsSleeve});

        jPanel1Layout.linkSize(SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.linkSize(SwingConstants.VERTICAL, new java.awt.Component[] {txtHeight, txtWeight, txtBust, txtWaist, txtHip, txtInseam, txtNeck, txtSleeve});

        

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 420, Short.MAX_VALUE)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    
	public void setTxtHeight(String str){
		this.txtHeight.setText(str);
	}
	
	public void setTxtWeight(String str){
		this.txtWeight.setText(str);
	}
	
	public void setTxtBust(String str){
		this.txtBust.setText(str);
	}
	public void setTxtWaist(String str){
		this.txtWaist.setText(str);
	}
	
	public void setTxtHip(String str){
		this.txtHip.setText(str);
	}
	
	public void setTxtInseam(String str){
		this.txtInseam.setText(str);
	}
	
	public void setTxtNeck(String str){
		this.txtNeck.setText(str);
	}
	
	public void setTxtSleeve(String str){
		this.txtSleeve.setText(str);
	}
    // Variables declaration - do not modify                     
    private JComboBox gender;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JSlider jsHeight;
    private JSlider biCristal;
    private JSlider jsBitroch;
    private JSlider jsWaist;
    private JSlider jsHip;
    private JSlider jsInseam;
    private JSlider jsNeck;
    private JSlider jsSleeve;
    private JTextField txtHeight;
    private JTextField txtWeight;
    private JTextField txtBust;
    private JTextField txtWaist;
    private JTextField txtHip;
    private JTextField txtInseam;
    private JTextField txtNeck;
    private JTextField txtSleeve;
    // End of variables declaration                   
}
